### ISSUE TITLE
Run as administrator the first time you build the app with VS2013

### ISSUE THREAD

**Issue by QuantForgeSoftware** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#13]
Hi Justin, I was just giving your project a try with VS2013r4 and the build failed. When it tries to build for the first time, you get:
  ------ Ensuring correct global installation of package from source package directory: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\EXTENSIONS\1MTH3BKD.CZX\packages\vs-mda

and a message that this is not installed globally so the build tries to install it locally. If you are not running VS as administrator, it will fail. After this is built once, then starting VS up normally works just fine. Thanks for your great project!

**Comment by Justin-Credible** [comment]
I have noticed this as well-- I think this is an issue with the Visual Studio Tools for Apache Cordova CTP. Once the 1.0 version is out I can re-evaluate at that time.
