### ISSUE TITLE
Visual Studio 2015 PRE - opening .sln

### ISSUE THREAD

**Issue by DeanB2015** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#14]
Justin,
I just tried viewing the repository in VS2015 Pre. Unfortunately, I get "incompatible with the current edition"
![vs_error_incompatible](https://cloud.githubusercontent.com/assets/10567383/7432582/6e1d6d2a-eff7-11e4-9c62-1934d879b64d.PNG)

Have you used VS2015 Apache Cordova App?  There are a significant number of changes compared with previous versions.

**Comment by Justin-Credible** [comment]
I was on the "Preview" release of VS2015, and I just updated to the VS2015 RC/PRE release today. I see the same message as you. I'm working on updating the solution now!

**Comment by DeanB2015** [comment]
Justin,
Thanks for the update.  FYI, article on migration path from previous VS Projects:

https://www.visualstudio.com/en-us/features/cordova-known-issues-vs.aspx

I'm using VS2015 RC/PRE and had some difficulties with it when I upgraded from VS2015 CTP. I hope you don't have these problems, but my final solution was totally remove VS2015 and all 3rd party.  Not fun and it took awhile, but it was the only way for everything to run smoothly.

**Comment by Justin-Credible** [comment]
Thanks for the link, it should help.

I was struggling with this last night, definitely not as easy as the previous upgrades. I am seeming some weirdness-- I used to be able to right-click on the project and select properties to be able to view the TypeScript build settings in VS2013, but this no longer shows up in 2015 RC/PRE. Not sure if this is a bug or by design.

Also, I'm not clear on how the appBundle.js gets generated as I don't see any after build targets. I'm assuming it must be inside of the extension. I saw browserify in the node_modules directory. It would be nice if there was some documentation on how it is generated and what ordering it uses.

**Comment by DeanB2015** [comment]
Justin,

vs2013 to VS2015 is a big difference and VS2015CTP5 to VS2015 RS/Preview is just as big. I believe the right click functionality is by design.

I would suggest running the blank TypeScript Apache Cordova Apps (File > New > Projects ) as a starter to confirm everything is working correctly.  Unfortunately, I had a previous project that I was testing and it didn't work so I tried a blank default hello world version and that didn't work either. Long story short, removed all VS2015 and 3rd party, reinstalled and now it's working. Very long day!

Took me awhile to figure out appBundle, but it's taking all the .ts files from the entire project and combing them into one (1)  large appBundle.js.  Very different from previous versions since the generated .js would each have their unique names. Not sure if they can be configured/modified. 

This is the latest video on how to use VS2015 with Apache Cordova.  It was created for Build 2015.  I haven't had time to check it out, but I'm sure it will answer your questions.

http://channel9.msdn.com/events/Build/2015/2-706

**Comment by thomasthiry** [comment]
I'm facing the exact same issue. I couldn't download the Visual Studio Tools for Apache Cordova for 2013 so I upgraded to 2015RC.
Hope you find a solution, your project looks great to get started on mobile development!

**Comment by Justin-Credible** [comment]
Working on this right now and it is almost ready!

**Comment by thomasthiry** [comment]
Great, thanks for the good work!

**Comment by thomasthiry** [comment]
Great, I'll check it out. Thanks!
