### ISSUE TITLE
Enable linting of TypeScript files

### ISSUE THREAD

**Issue by Justin-Credible** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#17]
Linting used to work in VS2013 with WebEssentials and a TSLint.json file. However, in 2015 RC0 it doesn't seem to be working. I need to figure out why it doesn't work any more and re-enable support for linting.

**Comment by Justin-Credible** [comment]
I checked on this again today in VS2015 RC with the latest WebEssentials plug-in. It still isn't respecting the `tslint.json` in the project root even after adding WebEssentials solution settings.

**Comment by aloisdg** [comment]
Hello,

You may want to check this [issue](https://github.com/madskristensen/WebEssentials2015/issues/27).

**Comment by Justin-Credible** [comment]
Thanks for the info!
