### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by kelong** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#18]
When I try to run in the ripple Android - Nexus (Galaxy) (also another platforms): 

SCRIPT5009: Unhandled exception at line 17, column 1 in ms-appx://justincredible.sampleapp/www/scripts/Main.js
0x800a1391 - JavaScript runtime error: 'JustinCredible' is undefined
Main.js (17,1)
HTML1300: Navigation occurred.
index.html
deviceready has not fired after 5 seconds.
Channel not fired: onPluginsReady
Channel not fired: onCordovaReady
Channel not fired: onDOMContentLoaded
SCRIPT5022: Unhandled exception at line 66, column 211 in ms-appx://justincredible.sampleapp/www/lib/ionic/js/ionic.bundle.min.js
0x800a139e - JavaScript runtime error: [$injector:modulerr] http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=JustinCredible.SampleApp.Application&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.13%2F%24injector%2Fnomod%3Fp0%3DJustinCredible.SampleApp.Application%0A%20%20%20at%20Anonymous%20function%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A406)%0A%20%20%20at%20a%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A34)%0A%20%20%20at%20Anonymous%20function%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A289)%0A%20%20%20at%20Anonymous%20function%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A66%3A44)%0A%20%20%20at%20s%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A38%3A300)%0A%20%20%20at%20g%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A65%3A399)%0A%20%20%20at%20ab%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A69%3A133)%0A%20%20%20at%20d%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A48%3A379)%0A%20%20%20at%20tc%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A49%3A172)%0A%20%20%20at%20Jd%20(ms-appx%3A%2F%2Fjustincredible.sampleapp%2Fwww%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A48%3A1)
ionic.bundle.min.js (66,211)
APPHOST9623: The app couldn’t resolve ms-appx://justincredible.sampleapp/images/touch-cursor.png because of this error: RESOURCE_NOT_FOUND.
adding proxy for Device
adding proxy for Notification
adding proxy for File
Ripple :: Environment Warming Up (Tea. Earl Gray. Hot.)
ripple.js (37,13099)
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
ripple.js (50,28958)
Failed to load resource: the server responded with a status of 404 (Not Found)
ripple.js (50,28958)
cordova :: Initialization Finished (Make it so.)
ripple.js (37,13099)
Failed to load resource: the server responded with a status of 404 (Not Found)
appBundle.js (0,0)
Uncaught Error: cordova already defined
cordova.js (104,0)
Current window: http://localhost:4400/index.html
Uncaught ReferenceError: JustinCredible is not defined
Main.js (17,1)
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=JustinCredible.SampleApp.Application&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.13%2F%24injector%2Fnomod%3Fp0%3DJustinCredible.SampleApp.Application%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A37%3A417%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A412%0A%20%20%20%20at%20a%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A53)%0A%20%20%20%20at%20x.bootstrap%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A296)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A66%3A116%0A%20%20%20%20at%20s%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A38%3A302)%0A%20%20%20%20at%20g%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A65%3A399)%0A%20%20%20%20at%20ab%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A69%3A135)%0A%20%20%20%20at%20d%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A48%3A381)
ionic.bundle.min.js (37,417)
Ripple :: Environment Warming Up (Tea. Earl Gray. Hot.)
ripple.js (37,13099)
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
ripple.js (50,28958)
Failed to load resource: the server responded with a status of 404 (Not Found)
ripple.js (50,28958)
cordova :: Initialization Finished (Make it so.)
ripple.js (37,13099)
Failed to load resource: the server responded with a status of 404 (Not Found)
appBundle.js (0,0)
Uncaught Error: cordova already defined
cordova.js (104,0)
Current window: http://localhost:4400/index.html
Ripple :: Environment Warming Up (Tea. Earl Gray. Hot.)
ripple.js (37,13099)
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
ripple.js (50,28958)
Failed to load resource: the server responded with a status of 404 (Not Found)
ripple.js (50,28958)
cordova :: Initialization Finished (Make it so.)
ripple.js (37,13099)
Uncaught Error: cordova already defined
cordova.js (104,0)
Failed to load resource: the server responded with a status of 404 (Not Found)
appBundle.js (0,0)
Uncaught ReferenceError: JustinCredible is not defined
Main.js (17,0)
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=JustinCredible.SampleApp.Application&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.13%2F%24injector%2Fnomod%3Fp0%3DJustinCredible.SampleApp.Application%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A37%3A417%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A412%0A%20%20%20%20at%20a%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A53)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A52%3A296%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A66%3A116%0A%20%20%20%20at%20s%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A38%3A302)%0A%20%20%20%20at%20g%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A65%3A399)%0A%20%20%20%20at%20ab%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A69%3A135)%0A%20%20%20%20at%20d%20(http%3A%2F%2Flocalhost%3A4400%2Flib%2Fionic%2Fjs%2Fionic.bundle.min.js%3A48%3A381)
ionic.bundle.min.js (66,0)
Current window: http://localhost:4400/index.html?enableripple=cordova-3.0.0-NexusGalaxy
Current window: http://localhost:4400/index.html

**Comment by Justin-Credible** [comment]
I tried using Ripple, iOS, and Android and all three targets worked for me.

From the error log you posted it looks like the `JustinCredible` namespace isn't available. All of the TypeScript code is compiled into `scripts/appBundle.js` and this is where the `JustinCredible` namespace is located which `Main.js` invokes on startup. I would check to make sure this file is present. Perhaps your TypeScript compiler or Visual Studio is not properly producing the `appBundle.js` file.

**Comment by kelong** [comment]
Yes, you are right, appBundle.js doesnt exists.
What I see in jsproj that there is $(MSBuildProjectDirectory)\www... for bundling
but I think that $(MSBuildProjectDirectory) is for main solution folder.
Can I check it somehow ?

**Comment by Justin-Credible** [comment]
The value of the `$(MSBuildProjectDirectory)` variable is the location at which the current project file is located (in this case the `.jsproj` file), so I believe that path is correct.

It sounds like you might have issues with your TypeScript compiler. I would suggest creating a new blank Visual Studio for Apache Cordova project using TypeScript (from the File > New Project) menu and ensuring the TypeScript is properly compiled in that case.

**Comment by kelong** [comment]
Ok, thank you. Yes, my typescript compiler wasn't building. I installed typescript 1.5 beta from typescriptlang site. Then my project asked me to update typescript tools inside the project.
Now your project is building correctly, however I still have the same issue, but now output says:

The source map 'angular-sanitize.min.js.map' for file 'C:\Ionic-TypeScript-MDHA-Starter-master\Sample-App\www\lib\ionic\js\ionic.bundle.min.js' could not be read from the specified location due to error 'Exception of type 'TypeScriptSourceMapReader.SourceMapReadFailedException' was thrown.'.The program '[1] http://localhost:4400/index.html?enableripple=cordova-3.0.0-NexusGalaxy: WebKit' has exited with code -1 (0xffffffff).

Thanks.

**Comment by kelong** [comment]
Ok, I installed Windows 10 build 10130 (earlier I was working on Windows 8.1 pro), installed VS 2015RC + nodejs, and now everything works (except one error favicon not found).
In offline mode there are 2 errors: "Failed to load ripple.js (not found)"  and "Failed to load resource: net::ERR_NAME_NOT_RESOLVED" 5991.png (no idea what is it :) ).
Thanks.

**Comment by Justin-Credible** [comment]
Cool-- glad you got it working.

Yeah, I've seen 404s in the dev console when running in a browser. Usually these are related to the `ripple.js` or `cordova.js` files (correctly) not being available during development.
