### ISSUE TITLE
Filename Can Make Ordering Of Generated appBundle.js To Be Wrong => RunTimeErrors

### ISSUE THREAD

**Issue by ahmedalejo** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#19]
Hi, i´ve been craving for aTypescript Cordova project sample that works on VS2015 RC.

I ported my project to Typescript Cordova project(that outputs individual js files) 
From VS 2013 Update 4 (the same project worked in VS2015 CTP 6) to VS2015 RC 
(which compiles ts files of a Typescript Cordova prject to appBundle).

After the port my code stopped working due to file concatenation order error.

this is noticed when having a base class dependency in another file

your project compile because of the names of the files. Typescript compiler orders files without `//<reference path="path/to/dependency.ts">`, alphabetically 

meaning that _BaseController.ts_, _CategoryController.ts_ and _BaseElementDirective.ts_ and _IconPanelDirective.ts_ are compiled and concatenated correctly

while **BaseController.ts**, **AttendanceController.ts** and **BaseElementDirective.ts** and **AppPanelDirective.ts** will compile but aren´t concatenated correctly.

the following won´t work (as expected)

``` typescript
//file A.ts without reference tag
module JustinCredible {
   export class A extends B{}
}

//file B.ts
module JustinCredible {
   export class B {}
}

//file C.ts
module JustinCredible {
   export class C extends B{}
}
```

```
//appBundle.js - wrong concat order
  - file A
  - file B
  - file C
```

```
//appBundle.js - expected concat order(B.js before A.js)
  - file B
  - file C
  - file A
```

While the following will work as expected

``` typescript
//file A.ts with reference tag
/// <reference path="B.ts" />
module JustinCredible {
   export class A extends B{}
}

//file B.ts
module JustinCredible {
   export class B {}
}

//file C.ts
module JustinCredible {
   export class C extends B{}
}
```

Note the reference tag in A.ts

The names of your file didn´t make this to surface.

 what a coincidence

**Comment by Justin-Credible** [comment]
Wow, that is quite a coincidence. I remember when I ported from VS2013 to 2015 I wondered how it would handle ordering of the TS files. Because it worked without any changes I just assumed it was able to figure out the order somehow, but turns out I just got really lucky.

My other projects that utilize this project have also been lucky as I have no controllers that start with an A or B.

Thanks for the feedback!

I'll see if I can get reference comments added, or maybe add a `_references.ts` file.

**Comment by ahmedalejo** [comment]
No worries.

But i did learn a lot from your project structure.

Great job.

i had a bigger problems after migrating.

i used the following pattern to reduce hardcoded string

``` typescript
//file module.ts
module app.books{
    "use strict";

    export var angularModule = angular.module("app.books", [/*other dependencies*/])
}
//file book.service.ts
module app.books{
    "use strict";

    export class BookService extends core.AbstractNetworkService {
        static id = "BookService ";
       //code omitted
    }
    angularModule.service(BookService.id, BookService)
}

//file booklist.controller.ts
module app.books{
    "use strict";
    export class BookListController extends core.RefreshableController {
        static id = "BookListController";
        static $inject = [BookService.id];
        constructor(private logbookService: LogbookServicer) {
            super(BookListController.id);
    }
    angularModule.controller(BookListController.id, BookListController)
}
```

this tremendously reduces refactory work.
For example when you want to turn `BookService` to a `OfflineCapableBookService` 
you would just do a rename of  `BookService` and change the id if needed

But for me
`BookService` wasn´t concatenated before `BookListController`
making `BookService.id` unavailable.

i´m trying integrate to with OnsenUI(stated this just for the sake of completeness)

**Comment by Justin-Credible** [comment]
Added a `_references.ts` with just the base components that should load first appears to fix the issue. Thanks for all the detailed info on this one!
