### ISSUE TITLE
Windows 8.1 app crash

### ISSUE THREAD

**Issue by Alphapage** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#20]
Hello,

I tried your great starter project and I tried to run on Windows universal app, but the app is crashing as soon as I click on a settings submenu or the reorganize categories menu.

I don't know why the app is crashing because only an ugly message is displayed redirecting to another VS debugger window.

Thanks in advance for your help.

**Comment by Justin-Credible** [comment]
I looked into this just now and it appears to be an issue with Visual Studio's DOM debugger. [This StackOverflow article](http://stackoverflow.com/questions/30464522/why-is-cordova-windows-8-app-causing-an-unhandled-win32-exception-occurred-in-ww) seems to confirm what I am seeing.

There are two workarounds:
1. Close the DOM Explorer tab that is open in Visual Studio
2. Detach the Visual Studio debugger completely using Debug > Detach All
