### ISSUE TITLE
Unit Test Framework

### ISSUE THREAD

**Issue by nathanpride** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#21]
I've been looking into how to do this (jasmine) and I'm not progressing as fast as I would like, I'm sure others would like to have a unit test project ready as part of you boiler plate project.

This intent is to test the logic not the UI, although of cause that would be the next request :)

Great job by the way!

**Comment by Justin-Credible** [comment]
Thanks!

Great suggestion by the way. I've been thinking about doing this for some time now and I think I have some ideas. I'll look into it!

**Comment by Justin-Credible** [comment]
I've added support for the Karma test runnier and Jasmine test framework to the [sister project](https://github.com/Justin-Credible/Ionic-TypeScript-Starter). You can take a look at it and see if it helps you.

I'm still working on porting the code to this repository.
