### ISSUE TITLE
VS2013 -Error when opening the project

### ISSUE THREAD

**Issue by adrienrx** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#35]
I get this error when i open the solution : 
D:\Projects\Ionic-TypeScript-MDHA-Starter-master\Sample-App\JustinCredible.SampleApp.jsproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.TypeScript.MDA.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\Projects\Ionic-TypeScript-MDHA-Starter-master\Sample-App\JustinCredible.SampleApp.jsproj

**Comment by Justin-Credible** [comment]
I'm not sure this project will open in VS2013. I would suggest using VS2015 RC and the latest TypeScript 1.5 beta.

**Comment by khalla** [comment]
Yeah, it did run on a windows 10 insider preview with visual studio 2015 RC, although i can deploy to windows phone 8.1, but not to android galaxy tab 3

Cheers

**Comment by Justin-Credible** [comment]
I'm going to go ahead and close this for now since VS2013 is not supported.
