### ISSUE TITLE
VS2015 release

### ISSUE THREAD

**Issue by kelong** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#37]
Hi,
After installing Visual Studio 2015 Final and open newest version of project
I have the following error:
build: accessors are only available when targeting ecmascript 5 and higher.
Tried to edit csproj and added:
<TypeScriptTarget>ES5</TypeScriptTarget>
but it doesn't work.
Any ideas ?

Thanks.

**Comment by khalla** [comment]
Hi,
I had that issue also.
You need to install typescript 1.5 beta, use nuget manager or node (npm).

Cheers,
Renato

**Comment by alexangas** [comment]
I followed the instructions [here](https://github.com/Microsoft/cordova-docs/blob/master/tutorial-gulp/gulp-typescript.md) to fix this, specifically the creation of a tsconfig.json

Previously I created a package.json which has the line `"typescript":"latest"`.

**Comment by khalla** [comment]
I did none of that, just used nuget to get Microsoft TypeScript package after clone the git project in VS2015.

Make it is worth noting that i'm running on a windows 10 Insider preview OS

**Comment by kelong** [comment]
khalla:
You mean Microsoft Typescript Compiler v 1.4.0 ?
Did you uninstall the typescript tools from programs ?
I am running windows 10 enterprise build 10240.

**Comment by alexangas** [comment]
In VS2015 RTM I can only see the Microsoft TypeScript Compiler v1.4.0 in NuGet (even with Prerelease turned on), not v1.5.0.

**Comment by alexangas** [comment]
Just tried again from scratch and following [MS' instructions here](https://github.com/Microsoft/cordova-docs/blob/master/tutorial-gulp/gulp-typescript.md) before build resolves this issue. You don't have to create a gulpfile, but you do need tsconfig.json.

**Comment by Justin-Credible** [comment]
I've added a section to the readme file for this; you have to manually install TypeScript 1.5 beta which you can obtain from the TypeScript website:

> Finally, you'll need the 1.5 beta version of TypeScript (VS2015RC currently ships with TypeScript 1.4). The 1.5 beta can be obtained from the [TypeScript Homepage](http://www.typescriptlang.org) or via the direct [download page](https://visualstudiogallery.msdn.microsoft.com/3e5ba71c-abea-4d00-b81b-a62de3ad3d53).

I'm also planning to investigate changes in VS2015 RTM and attempt to utilize `package.json` and `tsconfig.json` configuration files to make this project operate closer to its [sister project](https://github.com/Justin-Credible/Ionic-TypeScript-Starter).

**Comment by khalla** [comment]
To kelog:
Yes, i ment TypeScript 1.5 beta.

Justin updated this issue, with a more detail requirements for setup vs 2015.

Cheers

**Comment by alexangas** [comment]
It's worth noting that TypeScript 1.5 [reached RTM](http://blogs.msdn.com/b/typescript/archive/2015/07/20/announcing-typescript-1-5.aspx) alongside VS2015.

**Comment by Yaojian** [comment]
Using VS2015 with TypeScript 1.5, I still get the error  
`TS1056: Build: Accessors are only available when targeting ECMAScript 5 and higher.`.

I added `TypeScriptTarget` in `jsproj` but no help.

**Comment by khalla** [comment]
Yaolin,

You should check two things:
1. Project properties should define Module System and ECMAScript version:

![screenshot_1](https://cloud.githubusercontent.com/assets/143278/8870339/151b10b2-31e5-11e5-9ae9-1cd169e8c035.png)

2- If the above is set, check if you have node.js installed...  
if it is, go to command window, navigate to the project path and install typescript with the following command:

```
  npm install -g typescript
```

Cheers,
Renato

**Comment by Yaojian** [comment]
@khalla My project is a cordova project , so there is no such project properties page

**Comment by khalla** [comment]
@Yaojian 

Ok, i see.

Instaed check:

Menu Tools - Options 

In options chose Text Editor - TypeScript . Project:

![screenshot_3](https://cloud.githubusercontent.com/assets/143278/8874543/d3164838-3209-11e5-98b5-9921df7e525a.png)

Op option Compile on Save, choose module type (AMD) and then  choose ECMAScript5.

It should compile now

Cheers

**Comment by kelong** [comment]
I uninstalled the RTM version 1.5.3 of Typescript tools.

I installed 1.5.0.0 beta.
Changed settings in Visual Studio.

Tried to install typescript with npm:

 npm install -g typescript
C:\Users\kelte\AppData\Roaming\npm\tsc -> C:\Users\kelte\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\kelte\AppData\Roaming\npm\tsserver -> C:\Users\kelte\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
typescript@1.5.3 C:\Users\kelte\AppData\Roaming\npm\node_modules\typescript

Why the hell it still points to the RTM version which I uninstalled ?

And project still no compile, the same errors.

**Comment by IlieCiotir** [comment]
You need to add a **tsconfig.json** file in the **Sample-App\scripts** with the following content:

``` javascript
{
"compilerOptions": {
    "target": "es5",
    "out": "www/scripts/appBundle.js",
    "sourceMap": true,
    "removeComments": true,
    "sourceRoot": "/"
    }
}
```

The pull request with the fix. https://github.com/Justin-Credible/Ionic-TypeScript-MDHA-Starter/pull/39

**Comment by Justin-Credible** [comment]
I've merged in the addition of the tsconfig.json file and can confirm this fixes the issue on my machine. Thanks for the contribution!

Unfortunately I am currently suffering from [this](https://connect.microsoft.com/VisualStudio/feedback/details/1573191/visual-studio-2015-typescript-cordova-project-is-giving-the-error-the-debugger-cannot-continue-running-the-process-unable-to-start-debugging-when-trying-to-run-debug) issue, so I can't start/debug the project. I'm planning to re-install Windows next week when Windows 10 comes out, so hopefully I can keep looking into the strange issues introduced by the RTM of 2015.
