### ISSUE TITLE
Investigate removing controller/service constructors and set injected properties programmatically

### ISSUE THREAD

**Issue by Justin-Credible** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#38]
Currently, to add an injected property you must update 4 things:
- Inject decorator array
- Private instance variable declaration
- Constructor parameters
- Set instance variable in constructor

This is time consuming and is error prone as the order of the inject array must match the constructor array.

Instead, we can remove the constructors for all controllers and allow the BaseController to perform the setting of the instance variables.

With this code change there will be only two steps to when adding an injected property (inject array and instance variable) and as long as the two names match there will not be ordering issues.

In order to achieve this for services as well, services will need to inherit from a BaseService.

**Comment by Justin-Credible** [comment]
Additionally, place the resulting `ID`, `$inject`, and private instance variables in a region called "Configuration" at the start of each class.

**Comment by wmalgadey** [comment]
It may not be a big advantage, but the point

> Constructor parameters

could be solved with a TypeScript feature "Parameter Properties" (http://www.typescriptlang.org/Handbook#classes-privatepublic-modifiers)

you can create and initalize a property in the construtor by typeing the keyword `private`, `protected` or `public` in front of the parameter-Name:

```
constructor(private $q) {
}

private aFunctionToUse() {
    this.$q.waitAll(...);
}
```

is equivalent to:

```
private $q: any
constructor(private $q: any) {
    this.$q = $q;
}

private aFunctionToUse() {
    this.$q.waitAll(...);
}
```

**Comment by Justin-Credible** [comment]
Ah, great suggestion! I like your solution better as there is less magic. My solution requires you to know that the `BaseController` will take care of setting the instance variables, whereas your solution uses a known TypeScript language feature.

Thanks for the heads up!
