### ISSUE TITLE
Move get categories() ?

### ISSUE THREAD

**Issue by alexangas** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#43]
Do you think [get categories](https://github.com/Justin-Credible/Ionic-TypeScript-MDHA-Starter/blob/master/Sample-App/scripts/Services/Utilities.ts#L547) should be moved, instead of hanging out in a generalised class like Utilities.ts?

Maybe RootController? Or somewhere more specific?

**Comment by Justin-Credible** [comment]
Yeah, that is a good suggestion. I agree that it doesn't really fit well in `Utilities.ts`. I can move it to `Configuration.ts` as a part of the work done in #42.
