### ISSUE TITLE
Update cordova to 5.1.1

### ISSUE THREAD

**Issue by alexangas** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#45]
This might be a good idea to ensure the security fix in [Android 4.0.2](http://cordova.apache.org/announcements/2015/05/26/android-402.html) is the [platform default](https://cordova.apache.org/news/2015/06/10/tools-release.html). It may not be necessary but might be better on the safe side?

Happy to test things still work and submit to a PR for this.

**Comment by Justin-Credible** [comment]
I agree, it should definiately be at 5.0.0 or newer. It looks like the VS2015 RTM now defaults to 5.1.1, so I'll update this as a part of #48.
