### ISSUE TITLE
Switch plugins to npm repository

### ISSUE THREAD

**Issue by alexangas** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#46]
Cordova plugin references should be updated to [use the npm repository](http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html). Happy to research this and submit a PR.

It's worth noting that MS need to update VS2015 for these new IDs to show up in the UI, which might throw some people off.

**Comment by Justin-Credible** [comment]
It looks like the RTM of VS2015 has updated the plugin IDs to use the new npm style identifiers instead of the old Cordova plugin IDs, so there might not be any user confusion with this.

I'll take care of this with the rebuild of the project file for #48.
