### ISSUE TITLE
Configure Cordova 5 security model

### ISSUE THREAD

**Issue by alexangas** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#47]
Best practice for Cordova 5 seems to be to use the new whitelist plugin and configure it, as [suggested here](https://github.com/Microsoft/cordova-docs/blob/master/tutorial-cordova-5/cordova-5-security.md).

Happy to submit a PR for this.

**Comment by Justin-Credible** [comment]
Fits right in with the work for #45, #46, and #48.
