### ISSUE TITLE
VS Android virtual machine issue (rebuild project file for VS2015 RTM)

### ISSUE THREAD

**Issue by kelong** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#48]
I was trying to run application on VS android emulator,
I had an error:
INSTALL_PARSE_FAILED_MANIFEST_MALFORMED
I changed AndroidManifest:
"activity android:name="MainActivity"></activity"
to:
"activity android:name="justincredible.sampleapp.MainActivity"></activity"
Application deployes,
however I still can't run it from android vm, I have popup: "Unfortunately, SampleApp has stopped".

**Comment by Justin-Credible** [comment]
I was able to reproduce this on the repository, but not a new sample project. This was working with VS2015 RC. I'm assuming something changed again between the RC and the RTM version of VS2015. I'll investigate further. This will likely be a rebuild of the project file again.
