### ISSUE TITLE
Solution to inject different variables to the directive

### ISSUE THREAD

**Issue by wmalgadey** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#50]
Do you have a solution to inject different services into the directive?

I have some directives which needs the `ng.ITimeoutService` or `$ionicSideMenuDelegate`.

**Comment by Justin-Credible** [comment]
This would require re-working the `BaseElementDirective` and `getElementDirectiveFactoryFunction` to work more like the `OnLoadDirective` and `getDirectiveFactoryParameters`.

Until this is implemented, you could use the following to obtain a reference to the services you need.

```
var $ionicSideMenuDelegate = angular.element(document.body).injector().get("$ionicSideMenuDelegate")
```

**Comment by wmalgadey** [comment]
I modified an earlier Version of your Starter-Project, but dumped it, to be more compatible to your current development.

Did you test your onLoadDirective? It doesn't work for me. It doesn't get constructed!

**Comment by Justin-Credible** [comment]
Yes, I've used the `OnLoadDirective` in another app and I haven't had any problems with it.

Here is an example of how to use it:

```
<img src="{{viewModel.imageUrl}}" on-load="controller.image_load()">
```

**Comment by Justin-Credible** [comment]
I also just added the ability to inject parameters into directives that extend `BaseElementDirective`.

**Comment by wmalgadey** [comment]
Great work :) Thank you very much.

And I just solved my problem with my attribute directive. I injected ngModel into the constructor. But that was the wrong idea. The ngModel is the controller and needs to be injected with the "required"-Attribute in the directive. It then will get injected to the link-Method.
