### ISSUE TITLE
Structure by Feature and Isolate Boilerplate from App Code

### ISSUE THREAD

**Issue by ricklove** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#65]
This is the best Ionic seed I could find for VS 2015. I plan to use it for an upcoming project.

However, when I first looked at it, I was a bit overwhelmed with the code organization.

I prefer a code structure that is organized by feature. With this organization, it would be easy to isolate the boilerplate (i.e. base classes, dev tools, etc.) from the app specific code.

I would suggest an organization that combines all the code for a specific feature into a single directory and isolates system, component, and app level code.

For example with the CloudSync, the files could be organized in the following way.
- App
  - Settings
    - Cloud Sync
      - CloudSyncController.ts
      - CloudSyncViewModel.ts
      - Cloud-Sync.html
- Components
  - IconPanel
    - IconPanelDirective.ts
- System
  - Directives
    - BaseElementDirective.ts
- Library
  - Ionicons

As it is currently, the cloud sync example is spread across multiple directories and making any changes to it requires tracking each of these down. In addition, the base classes that seldom change are mixed with the app specific files which clutters up the focus on feature development.

With the code organized by feature and only App specific code in the App folder, it would be easy to learn from this seed and see exactly where additions/changes can be made.

Also, structure by feature scales easily to support large apps. Even with hundreds of features, it is quick to find all the relevant code for a specific feature in one place.

**Comment by Jerome2606** [comment]
+1

**Comment by IlieCiotir** [comment]
+1

**Comment by Justin-Credible** [comment]
Just wanted to give an update-- working on this right now.
