### ISSUE TITLE
HttpInterceptor response not closing "Please Wait..."

### ISSUE THREAD

**Issue by Jerome2606** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#69]
Hi,

I have a button in my menu to switch between lang.
My code:

```
protected switchLang(): void {
            if (this.$translate.use() === 'fr') {
                this.$translate.use('de');
            } else {
                this.$translate.use('fr');
            }
        }
```

This works fine but the Please Wait... message doesn't disappear.

Here's the console log:

```
console-via-logger.js:173 HttpInterceptor.request: locales/de.json [Object]0: 
Object
blocking: true
cache: undefined
headers: Object
method: "GET"
params: ""
showSpinner: true
transformRequest: Array[1]
transformResponse: Array[1]
url: "locales/de.json"
__proto__: Object
length: 1
__proto__: Array[0]
console-via-logger.js:173 HttpInterceptor.response: locales/de.json [Object]0: 
Object
config: Object
    blocking: true
    cache: undefined
    headers: Object
    method: "GET"
    params: ""
    showSpinner: true
    transformRequest: Array[1]
    transformResponse: Array[1]
    url: "locales/de.json"
    __proto__: Object
data: Object
headers: (c)
status: 200
statusText: "OK"
__proto__: Object
length: 1
__proto__: Array[0]
```

What's the config.blocking = true in the response ?? How to close the Please Wait... on the Ok response?

**Comment by Justin-Credible** [comment]
The `HttpInterceptor` contains code that, by default, shows a blocking spinner message that prevents user input for the duration of the request.  Normally the message is dismissed after a response comes back. My guess would be that the response for the Json response is somehow different and not triggering the hide code. 

If you have access to the source for the translate service you can pass a `blocking: false` flag to the `$http` service call. 

I can't debug at the moment, but you could step through the response handlers in `HttpInterceptor` and see why it isn't triggering the hide code. 

Alternatively you can look in the request method and skip the spinner message in the case of requests that have URLs that end in Json. There is already some code that does this for home templates. Search for `.html` and you should see it. 

I'll leave this issue open so I can investigate and apply a fix for the started project later.

**Comment by Jerome2606** [comment]
Hi,

I finally make it works. I add a then function to translate:

```
protected switchLang(): void {
            if (this.$translate.use() === 'fr') {
                this.$translate.use('de').then(function(){});
            } else {
                this.$translate.use('fr').then(function(){});
            }
        }
```
