### ISSUE TITLE
device_resume fired two times launch twice /app/onboarding

### ISSUE THREAD

**Issue by Jerome2606** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#73]
Hi,

With my application I encountered twice fired of device_resume. I switch to second screen of onboarding and this make back the first screen.
If I add a console.log on line services.$location.path("/app/onboarding/splash") I remark that the event is launch twice for an unknown reason.

So I add a condition to the if:

```
if (!services.Configuration.hasCompletedOnboarding && services.$location.path().indexOf("/app/onboarding") === -1) {
```

**Comment by Justin-Credible** [comment]
Hello.

I've tested on a iOS device as well as in the browser and `device_resume` only fires once for me.

I'm not sure I understand the problem. Can you provide steps to reproduce?

**Comment by Jerome2606** [comment]
I encounter this problem on Android 5.0
