### ISSUE TITLE
Cannot find namespaces

### ISSUE THREAD

**Issue by adam3039** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#78]
I can launch the app fine in Ripple, and it functions properly, but in the .ts files such as Configuration.ts, Visual Studio 2015 cannot find the namespaces for classes like "Interfaces" and "moment". I've made no alterations to your code.

**Comment by Justin-Credible** [comment]
It sounds like you don't have the TypeScript definition files installed. Please check to ensure you've executed `gulp libs` and `gulp tsd`. You should have libraries populated in `www/lib` and typings in the `typings` directory. After executing `gulp tsd` you may need to re-open the project in VS for it to see the type definitions.
