### ISSUE TITLE
How to make it work in cordova CTP 3?

### ISSUE THREAD

**Issue by mark416** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#9]
The app is build with cordova CTP 2, and can not open in vs with cordova CTP 3.

Please advise how to make that wprk with CTP 3.Thanks

Mark

**Comment by Justin-Credible** [comment]
Hello Mark.

I'm using VS2013 w/ Update 4 and MDHA CTP 3 on my machine and I have not experienced any issues developing or building the project. Can you provide more information?

EDIT:  I also just installed the VS2015 Preview edition (which also includes MDHA CTP3) and was able to build and run without issue.

**Comment by mark416** [comment]
I guess you use CTP 2 in same computer, 

some files can not find if you use it on a new pc.
